import { useContext, useState, useEffect } from 'react';
import { Formik, Form } from 'formik';
import { useRouter } from 'next/router';
import FormikField from '../forms/FormikField';
import AuthContext from '../../context/AuthContext';
import Head from 'next/head';
import axios from 'axios';
import links from '../../config/links';
import { getCurrentUser } from '../../auth/Auth';

interface LoginComponentProps {}

const LoginComponent: React.FC<LoginComponentProps> = () => {
  const { setLoading, setUser } = useContext(AuthContext);
  const [userLocal, setUserLocal] = useState<any>('');
  const [errors, setErrors] = useState<any>({});
  const [showPassword, setShowPassowrd] = useState<boolean>(false);
  const router = useRouter();

  useEffect(() => {
    setUserLocal(getCurrentUser());
    if (userLocal) router.push('/');
  }, []);
  const initialValues = {
    email: '',
    password: '',
  };

  const handleSubmit = async (values: any) => {
    await axios
      .post(`${links.default}/auth`, {
        email: values.email.trim(),
        password: values.password,
      })
      .then((res) => {
        setLoading(false);
        localStorage.setItem('FBIdToken', `Bearer ${res.data.token}`);
        setUser(getCurrentUser() || null);
        router.push('/');
      })
      .catch((error) => {
        setLoading(false);
        console.log(error.response.data.message || '');
        // if (error.response.data.path[0] === 'general')
        //   toast.error(error.response.data.message);

        // setErrors(error.response.data);
      });
  };
  const signInWithGoogle = () => {};

  const handleShowPassword = () => setShowPassowrd(showPassword ? false : true);
  return (
    <>
      {!userLocal ? (
        <>
          <div>
            <Head>
              <title>Login</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
              <div className=" flex justify-center items-center">
                {/* container */}
                <div className="h-[550px] xs:h-[666px] w-[375px] font-roboto relative px-5">
                  <div className="pt-5 xs:pt-12 md:pt-13 w-[90%] m-0">
                    <img
                      className="object-cover object-center w-[15rem] h-w-[15rem] fixed transform -z-50 translate-x-[14rem] -translate-y-16 top-0"
                      src="/welcome_page/salad_plate.png"
                      alt="salad"
                    />
                    <img
                      className="object-cover object-center w-[15rem] h-w-[15rem] fixed transform -z-50 -translate-x-[4rem] translate-y-16 left-0 bottom-0"
                      src="/welcome_page/salad_plate_2.png"
                      alt="salad"
                    />
                    <h1 className=" text-2xl sm:text-3xl font-bold text-[#3d1c47]">
                      Login to your <br /> account
                    </h1>
                    <img
                      className="mt-8 h-[8rem] mx-auto object-cover object-center"
                      src="/logo_svg/logo_text_vertical.png"
                      alt="chef"
                    />
                  </div>
                  {/* form */}
                  <Formik onSubmit={handleSubmit} initialValues={initialValues}>
                    <Form>
                      {/* form container */}
                      <div className="pt-4 pb-3">
                        <FormikField
                          name="email"
                          className="focus:outline-none text-sm"
                          placeholder="email@email.com"
                          // error={`${errors.path[0] === 'email' ? errors.message : ''}`}
                        />
                        <FormikField
                          name="password"
                          className="focus:outline-none text-sm"
                          placeholder="password"
                          type="password"
                          showPassword={showPassword}
                          onShowPassword={handleShowPassword}
                          // error={`${errors.path[0] === 'email' ? errors.message : ''}`}
                        />
                      </div>
                      <button
                        type="submit"
                        className="text-center w-full bg-[#3d1c47] text-gray-300 py-3 rounded-full"
                      >
                        Log in
                      </button>
                      <hr className="border-gray-300 my-4 mx-auto" />
                      <button
                        type="button"
                        onClick={signInWithGoogle}
                        className="my-2 flex text-center justify-center border border-gray-400 items-center w-full py-2 text-black rounded-md mt-3"
                      >
                        <img
                          className="h-5"
                          src="/logo_svg/google-icon.svg"
                          alt=""
                        />
                        <span className="pl-3">Continue with Google</span>
                      </button>
                      <button
                        type="button"
                        onClick={signInWithGoogle}
                        className="flex text-center justify-center items-center w-full py-2 text-white bg-[#039ae5] rounded-md mt-3"
                      >
                        <img
                          className="h-6 mb-1"
                          src="/logo_svg/facebook-icon.svg"
                          alt=""
                        />
                        <span className="pl-3">Continue with Facebook</span>
                      </button>
                    </Form>
                  </Formik>
                </div>
              </div>
            </main>
          </div>
        </>
      ) : null}
    </>
  );
};

export default LoginComponent;
